### ISSUE TITLE
More than two departures

### ISSUE THREAD

**Issue by oyvindhauge** [jonkristian/entur-card#10]
With the 0.91 release of Home Assistant, the Entur component allows for more than two departures from a bus stop. Adding support for this would be great:

https://www.home-assistant.io/components/entur_public_transport/
![image](https://user-images.githubusercontent.com/288557/55683123-778ab680-593c-11e9-9a45-127fe9486a45.png)

**Comment by oyvindhauge** [comment]
![image](https://user-images.githubusercontent.com/288557/55687810-7b84fb80-5971-11e9-96c4-163fff9a0821.png)

I did some changes to your component to get this. There are some issues that I would like to iron out. Maybe you could help?

1. It would be a lot nicer to get the departure_#3 to departure_#10 with a loop.
2. The parsing of the text in the departures (line) could be done better. There are probably other things that should be removed than the time and "ca.".
3. The delay is set to 0 for departure 3 to 10 because this info is not provided.

Nevertheless, I uploaded what I did if you care to have a look. I never do any coding so, please keep that in mind :-)
[entur-card.zip](https://github.com/jonkristian/lovelace-cards/files/3051910/entur-card.zip)

**Comment by leloberg** [comment]
You could also do a pull request on this repo, and do a merge request with your fixes :)

**Comment by oyvindhauge** [comment]
I thought maybe I/we should fix the "bugs" before doing a merge. I am Github noob, but will look into merging later :)

**Comment by jonkristian** [comment]
I had a bad crash with home assistant on my rpi with all my setup (flash card gave up), also about to move house so i haven't had time to work more on this. But I will get around to setting up a dev environment with home assistant and look into this ASAP. I will set up a develop branch for new PRs.

**Comment by jonkristian** [comment]
This is now available in my latest commit.
