### ISSUE TITLE
Add support to HACS

### ISSUE THREAD

**Issue by leloberg** [jonkristian/entur-card#12]
Would it be possible to add support for this component to HACS?

https://github.com/custom-components/hacs

**Comment by mattiasbrandt** [comment]
Details on how you can add it to to the HACS default repo
https://custom-components.github.io/hacs/developer/include_default_repositories/

**Comment by jonkristian** [comment]
I see some restructuring is needed, I've prepared this new folder layout. Also working on a build-system for this code and some rewrite. I am currently trying to finish my house so I can move in, so it's been a little slow recently but will try to find some time :)
