### ISSUE TITLE
http://xxx.xxx.xxx.xxx:8123/local/community/entur-card/entur-card.js:1:1 Uncaught SyntaxError: Identifier 't' has already been declared

### ISSUE THREAD

**Issue by phellarv** [jonkristian/entur-card#13]
Home Assistant 0.96.4 
Results in "No card type configured"

**Comment by jonkristian** [comment]
Could you please share your configuration.

**Comment by phellarv** [comment]
Installed the card via HACS.
Added 
resources:
  - type: module
    url: >-
      https://cdn.jsdelivr.net/gh/bramkragten/custom-ui@master/weather-card/weather-card.min.js
  - type: js
    url: /local/community/entur-card/entur-card.js
..... snip .....
  - badges: []
    cards:
      - entity: sensor.58_bjerkedalen_park_platform_10993
        hours_to_show: 6
        name: 58 mot Nydalen
        type: sensor
      - entity: sensor.58_bjerkedalen_park_platform_10996
        hours_to_show: 6
        name: 58 mot Tveita
        type: sensor
      - entity: sensor.60_okernbraten_platform_10902
        hours_to_show: 6
        name: 60 mot Sentrum
        type: sensor
      - entity: sensor.60_okernbraten_platform_10901
        hours_to_show: 6
        name: 60 mot Linderud
        type: sensor
      - - type: 'custom:entur-card'
          name: Rutetider
          show_clock: true
          show_next: true
          show_human: true
          show_extra_departures: true
          entities:
            - destination: Nydalen
              entity: sensor.58_bjerkedalen_park_platform_10993
              name: Bjerkedalen
    icon: 'mdi:bus'
    title: Buss

**Comment by jonkristian** [comment]
You have to check your indentations and configuration.
Type for example should be prefixed with `- type`.

Have a look here:
https://www.home-assistant.io/docs/configuration/troubleshooting/
https://www.home-assistant.io/lovelace/yaml-mode/
