### ISSUE TITLE
Mix of English and Norwegian in card

### ISSUE THREAD

**Issue by espizo** [jonkristian/entur-card#14]
All human readable time notations are in Norwegian.
Is it possible to change this to English?

![image](https://user-images.githubusercontent.com/75159/70050472-506dad00-15cf-11ea-808e-e93701ab4a2d.png)

**Comment by jonkristian** [comment]
Sorry for late reply, I've been moving house.
It should already be implemented, not sure if I ever tested it, but I'll take a look.

**Comment by jonkristian** [comment]
Should be resolved now.
