### ISSUE TITLE
Styling of show_next departure

### ISSUE THREAD

**Issue by espizo** [jonkristian/entur-card#15]
I want to show the next 3 departures from a bus stop, so I added `number_of_departures: 3` to configuration.yaml.

Is it possible to get all 3 departures in the same style? 

Now it looks like this:
![image](https://user-images.githubusercontent.com/75159/70052075-c7587500-15d2-11ea-878e-a56dfe0fbfae.png)

It _looks_ correct if I use `show_next: false` and `number_of_departures: 4`, but this obviously _hides_ the next departure, which I don't want.

**Comment by geeewizzz** [comment]
This card is great, but I have the same issue as @espizo . In a stop where I have listed several departures from the same line this issue becomes a problem. Also it seems to have a problem with defining the time until the next departure if the next departure is the next day (after midnigt)

<img width="455" alt="Screenshot 2020-04-28 at 23 30 20" src="https://user-images.githubusercontent.com/4536023/80539747-57df8980-89a8-11ea-9570-2e3cd9fb4a2b.png">

**Comment by jonkristian** [comment]
Hi, thanks for your kind words and sorry for the late reply. I've been quite busy lately but my schedule is starting to clear up.
I will take a look at this as soon as possible.

**Comment by jonkristian** [comment]
I've pushed quite a lot of changes now which also addresses this issue and hopefully to your likings. It should now be sufficient to use number_of_departures as next_departure will then be included in that list, show_next_departure should then be set to false.

Please let me know if this solved your problem.

**Comment by jonkristian** [comment]
Closing this for now, feel free to re-open if this didn't fix your issue.
