### ISSUE TITLE
Card not following theme

### ISSUE THREAD

**Issue by stianhoe** [jonkristian/entur-card#19]
Hi,
Excellent card. 
However, I'm not able to get the card to follow the theme formatting for text and icon.
This is what it looks like for me:
![image](https://user-images.githubusercontent.com/62373802/79231051-c7f8f600-7e65-11ea-9ef0-92e1d575061e.png)
As you see, the icons and text should be "gold", but stays in the default blue formatting.

**Comment by jonkristian** [comment]
Hi, thanks for your kind words and sorry for the late reply. I've been quite busy lately but my schedule is starting to clear up. I will take a look at this.

**Comment by jonkristian** [comment]
I've pushed quite a lot of changes now which also addresses theming. Please let me know if you experience any issues.
