### ISSUE TITLE
Showing a mix of Norwegian and English text

### ISSUE THREAD

**Issue by palengh** [jonkristian/entur-card#21]
This add-on is GREAT! Thank you for your effort putting this together, guys!

My Home Assistant is running in VirtualBox, using the standard .ova image from Home assistant. This issue might be related to the OS running english locale.

Still I would like to set all text for this to Norwegian. 

<img width="484" alt="Skjermbilde 2020-09-10 kl  08 18 39" src="https://user-images.githubusercontent.com/12332161/92689423-48515380-f33f-11ea-83d2-362c0a43330c.png">
Is it possible to override this, eg. by adding a language parameter to the add-on config?

**Comment by jonkristian** [comment]
Thank you, and thanks for reporting. I've actually seen this too, will take a look at it ASAP.

**Comment by jonkristian** [comment]
Took some time, but should be fixed in latest.
