### ISSUE TITLE
Mix of english an norwegian

### ISSUE THREAD

**Issue by henrikrox** [jonkristian/entur-card#23]
![2021-06-04 23_07_30-Dwains Dashboard - Home Assistant](https://user-images.githubusercontent.com/6884716/120862753-bdc61980-c589-11eb-818c-12d73f18e344.png)

Det brukes at, leaves etc

**Comment by jonkristian** [comment]
Hei, har du sjekket at du har siste kode og språkinstillingene dine?
Klarer ikke å reprodusere dette.
