### ISSUE TITLE
Show cancellations

### ISSUE THREAD

**Issue by toco1** [jonkristian/entur-card#25]
I love this card and using it a lot – but it does not seem to show cancellations. We have a lot of them here on the Østfoldbane (Vy) – while the card does show delays, it does not show cancellation it seems. Is this a limitation that comes from the entur-data?

**Comment by jonkristian** [comment]
I will have to look into this one, if entur sensor can show cancellations, I can add it to the card.

**Comment by jonkristian** [comment]
I've looked at the integration source code for entur and it looks like it doesn't support this, maybe create a ticket asking about it, feel free to re-open again if the situation changes.
