### ISSUE TITLE
Direction of routes

### ISSUE THREAD

**Issue by toco1** [jonkristian/entur-card#26]
As it is written in the description there is no way in the entur API to define a route from A to B but instead one can whitelist route IDs. The problem with route IDs is that they are the same regardless of the direction of a train. On smaller stations (Holmlia Stasjon in my case) where there is only one platform per direction, this works fine with whitelisting the platform. On bigger stations, as Oslo S for instance with 19 tracks, this becomes rather messy. Is there any way to define and filter the direction of a route?

**Comment by jonkristian** [comment]
I will have to look into this one, but if it's possible with the entur component, it is definitely possible to implement.

**Comment by jonkristian** [comment]
@toco1 I don't think this would be possible in the card unless it gets added in the entur component, maybe try creating a issue for that over [there](https://github.com/home-assistant/core/issues?q=is%3Aissue+label%3A%22integration%3A+entur_public_transport%22+is%3Aopen)?

Maybe one temporary solution could be to create a sensor template if you can find some attributes to filter on, then just use that sensor with the card.
