### ISSUE TITLE
Entity could not be found

### ISSUE THREAD

**Issue by jewiden** [jonkristian/entur-card#29]
Trying to set up entur-card, but card claims the entity can't be found.
In states-view the entity is available and has data as it should.

<img width="735" alt="image" src="https://user-images.githubusercontent.com/116989/164994253-13874cad-2f8f-4553-8fdb-ebbef2fc6560.png">

<img width="806" alt="image" src="https://user-images.githubusercontent.com/116989/164994285-38f8c9c6-1c1f-4e3a-aa72-50dbdc237672.png">

**Comment by jonkristian** [comment]
Sorry for the late reply? Did you ever get it working? I was going to suggest a restart if you have added the sensor the same time as installing my card?

**Comment by jonkristian** [comment]
Closing this for now, @jewiden feel free to re-open if you still experience this issue.
