### ISSUE TITLE
Filtering on destination name

### ISSUE THREAD

**Issue by pstray** [jonkristian/entur-card#31]
My local station has two tracks, and you would assume that they were reserved for trains in one direction, but sadly no ;)  It would be nice to actually filter departures shown on the destination name, since the line id is the same.  Thus, I am only interested in "R22 Ski" and "R22 Oslo S", but not "R22 Mysen" from my local station...

Would that be possible to implement?

**Comment by jonkristian** [comment]
Can you please send me `StopPlace` for that station?

**Comment by pstray** [comment]
That would be Tomter Stasjon, 'NSR:StopPlace:61897'

**Comment by jonkristian** [comment]
What this card does is to take a sensor and show the data from that sensor, so it's pretty basic like that. I see that entur allows you to expand platforms to create platform sensor, I wonder if you have looked at line whitelisting and possibly expand_platforms to get the correct data from a sensor which you can use? If that is a possible way to accommodate this?

**Comment by pstray** [comment]
No, not really... Seems that there is no specific track used for trains in one direction.  If trains towards Oslo S always were on track 1, then that would do it, but that is not the case, and both tracks are used for both directions.

This is also the case for trains passing through Oslo S btw... the do not always arrive or depart from the same track number every time.

**Comment by jonkristian** [comment]
Hmm, interesting challenge.

I wonder still, if there's a better/cleaner approach to this, rather than adding and building out this logic in the card, maybe it's possible to create a new sensor based on the ones from entur, where you can apply a filter, and then use that sensor for the card, what do you think?

**Comment by pstray** [comment]
Yes, that may probably work... if i find out how :)  But implementing issue #30 would also help a lot (at least with Oslo S)

**Comment by jonkristian** [comment]
I will take a look at that. Please do share if you're able to figure it out or if you get stuck, maybe I/or others can help. Could make for a good addition to the docs.

**Comment by jonkristian** [comment]
Closing this, I think the conclusion here is either a sensor template or getting it added in as a feature in the entur component.
