### ISSUE TITLE
2.0.0-beta GUI config does not show entur sensor. 

### ISSUE THREAD

**Issue by repvik** [jonkristian/entur-card#33]
I have an entur sensor "sensor.buss_flatasen_senter". This sensor is not available in the entity list on the card in the visual editor. 
<img width="378" alt="image" src="https://user-images.githubusercontent.com/1718917/227740591-f15290b1-2739-4c41-9927-fcb980e273ef.png">

Using yaml editor and switching back to visual editor doesn't help either.

**Comment by jonkristian** [comment]
Aha, good first issue for the beta. I did not think about sensors starting with something other than `sensor.transport*` , the code has a filter which filters through so you don't get all sensors but only those that is from entur, I might have to create a checkbox to disable that filter for those that have custom sensor names, or if there is some other common key we could filter on.

Maybe it's good enough to check if a sensor contains `route_id` attribute instead, I will test that and provide a fix.

**Comment by repvik** [comment]
Can't you filter on "entities provided by entur integration"? (And have a toggle to disable filter if someone clever creates a helper sensor for some reason)

**Comment by jonkristian** [comment]
That would be real nice but unfortunately afaik there is no way to say get all sensors via an integration. I have some new code coming up which filters on `route_id`, so for now I think that should be ok. Coming up in a couple of minutes :smile:

**Comment by repvik** [comment]
Works now.
