### ISSUE TITLE
Polymer being discontinued

### ISSUE THREAD

**Issue by Aviatorpaal** [jonkristian/entur-card#36]
Several references to Polymer in the JS file of Entur 1.0.0. This might just be credit to authors of Polymer.

Home Assistant will remove Polymer in 2023.5

From Core logs: `WARNING (MainThread) [frontend.js.latest.202304111] WARNING: Polymer will be removed from window in Home Assistant 2023.5. More info: https://developers.home-assistant.io/blog/2023/04/04/deprecating_polymer`

**Comment by jonkristian** [comment]
@Aviatorpaal 
Thanks for letting me know.

I just released 2.0.0 which takes care of this. Just a heads up, 2.0.0 contains a lot of changes, so you will have to set up the card(s) from scratch.
