### ISSUE TITLE
Uncaught ReferenceError: moment is not defined

### ISSUE THREAD

**Issue by leloberg** [jonkristian/entur-card#8]
Hei

Denne fungerer ved jevne mellomrom, men ganske ofte dukker ikke noe opp i skjermbildet, og jeg får følgende feilmelding i loggen:

2019-03-01 09:48:49 ERROR (MainThread) [frontend.js.latest.201902200] http://hassio.local:8123/local/custom_ui/entur-card/entur-card.js?v=2:158:20 Uncaught ReferenceError: moment is not defined

**Comment by oysteinjakobsen** [comment]
Opplever det samme, men feilen er helt systemmatisk. Om jeg gjør en refresh av en lovelace-fane der entur-kortet er så feiler det. Om jeg går til en annen fane, gjør en refresh og så går til lovelace-fanen med entur-kortet så fungerer det fint. Denne feilen er diskutert i forbindelse med andre kort også, så dette er nok mer et lovelace-problem. Moment.js rekker ikke å bli lastet før entur-kortet begynner å kjøre, så det feiler. Om man laster en annen fane istedet så rekker moment å bli lastet før man går til fanen med entur-kortet.

**Comment by leloberg** [comment]
Se der ja, da fungerte det her også :) Ok, det er i så fall en workaround inntil videre. Takk.

**Comment by erlsta** [comment]
En annen workaround er å lagre moment.js lokalt i stedet for å laste den fra nettet. Takk for kortet forresten. Fungerer glimrende! :-)

**Comment by leloberg** [comment]
Jeg forsøkte lagre den lokalt, og sette den øverst i resource-lista, men jeg må fortsatt refreshe på en annen tab. Gjorde du noe annet spesielt?

**Comment by erlsta** [comment]
Nei, jeg laster den bare slik:
```
  - url: /local/moment.js?v=2.001
    type: js
```
entur-card.js ligger i samme mappe.
