### ISSUE TITLE
Invalid date

### ISSUE THREAD

**Issue by leloberg** [jonkristian/entur-card#9]
Får følgende feil i komponenten på alle reiser. Forsøkte spore hvorfor det skjer, men har ikke klart finne noe enda. Kan noen verifisere om dette kun er hos meg?

![image](https://user-images.githubusercontent.com/8376070/55385023-82081300-552c-11e9-9746-c5afbb601d87.png)

**Comment by thomashpettersen** [comment]
Jeg har også samme problem, vet ikke når det oppsto. Men når jeg oppgraderte til 0.91.0 i dag, så så jeg at det var et problem der.

**Comment by jonkristian** [comment]
Gjerne sjekk develop branch om dette er i orden.

**Comment by leloberg** [comment]
Det er i orden for meg (i dev).

**Comment by thomashpettersen** [comment]
Funket for meg også.

**Comment by jonkristian** [comment]
Flottings!
